### ISSUE TITLE
FormattedString in bottom sheet crashes app when closing bottom sheet

### ISSUE THREAD

**Issue by rbudnar** [Akylas/nativescript-material-components#125]
### Make sure to check the existing issues in this repository 
Probably related to https://github.com/Akylas/nativescript-material-components/issues/81 and/or https://github.com/Akylas/nativescript-material-components/issues/78. My apologies if it is the same. 

### Which platform(s) does your issue occur on?
- Android emulator (Android 9.0, Pixel 2). I have not tested iOS since I don't have that set up yet.

### Please, provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it): CLI: 6.4.0

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/@nativescript/core/package.json` file in your project): "version": "6.4.1",
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) : "version": "6.4.1"
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
```
"@angular-devkit/build-angular": "0.803.25",
"@angular/cli": "8.3.25",
"@angular/compiler-cli": "8.0.0",
        "@angular/language-service": "~7.2.15",
        "@nativescript/schematics": "~0.4.0",
        "@ngtools/webpack": "^9.0.2",
        "@ngxs/devtools-plugin": "^3.6.2",
        "@types/jasmine": "~2.8.8",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "^12.0.10",
        "codelyzer": "~4.5.0",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~3.0.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~1.1.2",
        "karma-jasmine-html-reporter": "^0.2.2",
        "nativescript-dev-webpack": "~1.5.0",
        "prettier": "1.17.0",
        "protractor": "~5.4.0",
        "tns-core-modules": "^6.4.1",
        "ts-node": "~7.0.0",
        "tslint": "~5.11.0",
        "typescript": "3.4.5",
        "webpack-cli": "^3.3.5",
        "webpack-visualizer-plugin": "^0.1.11"
```
### Please, tell us how to recreate the issue in as much detail as possible. 
Add a basic bottom sheet and invoke as per docs. When a component that has a `<FormattedString>`  in it is displayed in the bottom sheet, the app will crash when the bottom sheet is closed.

### Is there any code involved? 
See playground:
https://play.nativescript.org/?template=play-ng&id=J4penn&v=3
Tap the button to open the bottom sheet; when you tap outside to close the app will crash. Comment out the formatted string button and it will work as expected. 

I get a stack trace like this:
```
 An uncaught Exception occurred on "main" thread.
Calling js method onDismiss failed
TypeError: child._bottomSheetClosed is not a function

StackTrace:
(file:///data/data/org.nativescript.preview/files/app/nativescript-material-bottomsheet/bottomsheet-common.js:30:19)
at localCallback(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:76:29)
at TextBaseCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/text-base/text-base-common.js:201:13)
at eachDescendant(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:82:10)
at ViewWithBottomSheetBase._bottomSheetClosed(file:///data/data/org.nativescript.preview/files/app/nativescript-material-bottomsheet/bottomsheet-common.js:29:21)
at (file:///data/data/org.nativescript.preview/files/app/nativescript-material-bottomsheet/bottomsheet-common.js:30:19)
at localCallback(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:76:29)
at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/layouts/layout-base-common.js:125:26)
at ViewCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view-common.js:915:14)
at eachDescendant(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:82:10)
at ViewWithBottomSheetBase._bottomSheetClosed(file:///data/data/org.nativescript.preview/files/app/nativescript-material-bottomsheet/bottomsheet-common.js:29:21)
at (file:///data/data/org.nativescript.preview/files/app/nativescript-material-bottomsheet/bottomsheet-common.js:30:19)
at localCallback(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:76:29)
at ContentView.eachChildView(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/content-view/content-view.js:70:13)
at ViewCommon.eachChild(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view-common.js:915:14)
at eachDescendant(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view-base/view-base.js:82:10)
at ViewWithBottomSheetBase._bottomSheetClosed(file:///data/data/org.nativescript.preview/files/app/nativescript-material-bottomsheet/bottomsheet-common.js:29:21)
at _whenCloseBottomSheetCallback(file:///data/data/org.nativescript.preview/files/app/nativescript-material-bottomsheet/bottomsheet-common.js:49:19)
at dismissCallback(file:///data/data/org.nativescript.preview/files/app/nativescript-material-bottomsheet/bottomsheet.js:198:57)
at BottomSheetDialogFragmentImpl.onDismiss(file:///data/data/org.nativescript.preview/files/app/nativescript-material-bottomsheet/bottomsheet.js:140:22)
at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
at com.tns.Runtime.callJSMethod(Runtime.java:1160)
at com.tns.Runtime.callJSMethod(Runtime.java:1138)
at com.tns.Runtime.callJSMethod(Runtime.java:1134)
at com.google.android.material.bottomsheet.BottomSheetDialogFragment_bottomsheet_61_32_BottomSheetDialogFragmentImpl.onDismiss(Unknown Source:20)
at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1503)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at **com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)**
```

**Comment by farfromrefug** [comment]
@rbudnar you dont give the version you are using for this plugin.
Could you please try again with latest and report

**Comment by rbudnar** [comment]
Sorry about that. Looks like my app and the playground was on 3.1.11. I updated to 3.2.3 and the problem now appears to be resolved. Thanks for the reply! I'll close this issue.
