### ISSUE TITLE
[Vue] Problem with close Bottom Sheet

### ISSUE THREAD

**Issue by wesoly935** [Akylas/nativescript-material-components#127]
- Android 

After open Bottom Sheet, whene i wan't to close it i get exception:
`
(this as any).$closeBottomSheet();
`
Is any way to close bottom sheet manually and pass param to parent view?

```
Exception:
System.err: Calling js method onTouch failed
System.err: TypeError: Cannot read property '$emit' of null
System.err:
System.err: StackTrace:
System.err: closeCallback(file:///app\src\bottomsheet\vue\index.ts:34:41)
System.err:     at _whenCloseBottomSheetCallback(file:///app\src\bottomsheet\bottomsheet-common.ts:87:38)
System.err:     at dismissCallback(file:///app\src\bottomsheet\bottomsheet.android.ts:247:35)
System.err:     at BottomSheetDialogFragmentImpl.onDismiss(file:///app\src\bottomsheet\bottomsheet.android.ts:185:21)
System.err:     at ViewWithBottomSheet._hideNativeBottomSheet(file:///app\src\bottomsheet\bottomsheet.android.ts:219:38)
System.err:     at _closeBottomSheetCallback(file:///app\src\bottomsheet\bottomsheet-common.ts:100:21)
System.err:     at ViewWithBottomSheetBase.closeBottomSheet(file:///app\src\bottomsheet\bottomsheet-common.ts:117:26)
System.err:     at Vue.$closeBottomSheet(file:///app\src\bottomsheet\vue\index.ts:42:28)
System.err:     at webpackHotUpdate.../node_modules/ts-loader/index.js?!../node_modules/vue-loader/lib/index.js?!./components/GalleryBottomSheet.vue?vue&type=script&lang=ts&.GalleryBottomSheet.onEditTap(file:///app\components\GalleryBottomSheet.vue?479c:68:18)
System.err:     at touch(file:///app\components\GalleryBottomSheet.vue?3c36:29:0)
```

**Comment by farfromrefug** [comment]
@wesoly935  what exception?

**Comment by wesoly935** [comment]
@farfromrefug updated, sorry, my mistake

**Comment by farfromrefug** [comment]
@wesoly935 are you sure you are not calling closeBottomSheet twice?

**Comment by wesoly935** [comment]
If i debuggin js script in Developers tools `_whenCloseBottomSheetCallback` is called twice.
But in Bottom Sheet view I have a label with `@tap` event and in it i calling $closeBottomSheet() only once.

**Comment by wesoly935** [comment]
Temporary: 
`this.$nextTick(() => (this as any).$closeBottomSheet(1));`
Resolve my problem, but passed `1` in argument is not received in `closeCallback`

**Comment by farfromrefug** [comment]
@wesoly935 right now passed argument is not sent to callback ...
but i am not sure to understand why the tick would solve it

**Comment by farfromrefug** [comment]
@wesoly935 could you test with latest versions?

**Comment by wesoly935** [comment]
No, I had problems with Bottom Sheet and I choosed other solution to display action modal.
