### ISSUE TITLE
Application crashes when using MDTextField

### ISSUE THREAD

**Issue by pazfelipe** [Akylas/nativescript-material-components#132]
I would like to use `< MDTextField/>` but everytime I insert it on my vue file my application crashes.

I'm adding it with `tns plugin add nativescript-material-textfield`.
In `main.js`, I've imported with 
```
import TextFieldPlugin from 'nativescript-material-textfield/vue'
Vue.use( TextFieldPlugin )
```

And, in my vue file, it's declared:
```
<MDTextField
    hint="Company name"
    returnKeyType="next"
    v-model="company"
/>
```

This is the error I've gotten:
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.google.android.material.textfield.TextInputLayout
System.err: Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class com.google.android.material.textfield.TextInputLayout
System.err: Caused by: java.lang.reflect.InvocationTargetException
System.err:     java.lang.reflect.Constructor.newInstance0(Native Method)
System.err:     java.lang.reflect.Constructor.newInstance(Constructor.java:343)
System.err:     android.view.LayoutInflater.createView(LayoutInflater.java:647)
System.err:     android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
System.err:     android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
System.err:     android.view.LayoutInflater.inflate(LayoutInflater.java:492)
System.err:     android.view.LayoutInflater.inflate(LayoutInflater.java:423)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)  
System.err:     androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303) 
System.err:     androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
System.err:     androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
System.err:     androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
System.err:     androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err:     android.os.Handler.handleCallback(Handler.java:873)
System.err:     android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: java.lang.IllegalArgumentException: The style on this component requires your 
app theme to be Theme.MaterialComponents (or a descendant).
System.err:     com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:248)
System.err:     com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:222)
System.err:     com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:150)
System.err:     com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:120)
System.err:     com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:424)
System.err:     com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:396)
System.err:     java.lang.reflect.Constructor.newInstance0(Native Method)
System.err:     java.lang.reflect.Constructor.newInstance(Constructor.java:343)
System.err:     android.view.LayoutInflater.createView(LayoutInflater.java:647)
System.err:     android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
System.err:     android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
System.err:     android.view.LayoutInflater.inflate(LayoutInflater.java:492)
System.err:     android.view.LayoutInflater.inflate(LayoutInflater.java:423)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)  
System.err:     androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err:     androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303) 
System.err:     androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
System.err:     androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
System.err:     androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
System.err:     androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
System.err:     androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err:     android.os.Handler.handleCallback(Handler.java:873)
System.err:     android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)    
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err:
System.err: StackTrace:
System.err:     Frame: function:'TextField.createNativeView', file:'file: app\src\textfield\textfield.android.ts:93:91
System.err:     Frame: function:'ViewBase._setupUI', file:'file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:511:30
System.err:     Frame: function:'', file:'file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:553:18
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:25
System.err:     Frame: function:'ViewCommon.eachChild', file:'file: node_modules\@nativescript\core\ui\core\view\view-common.js:915:13
System.err:     Frame: function:'ViewBase._setupUI', file:'file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:552:13
System.err:     Frame: function:'', file:'file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:553:18
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file: node_modules\@nativescript\core\ui\layouts\layout-base-common.js:125:25
System.err:     Frame: function:'ViewCommon.eachChild', file:'file: node_modules\@nativescript\core\ui\core\view\view-common.js:915:13
System.err:     Frame: function:'ViewBase._setupUI', file:'file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:552:13
System.err:     Frame: function:'', file:'file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:553:18
System.err:     Frame: function:'ContentView.eachChildView', file:'file: node_modules\@nativescript\core\ui\content-view\content-view.js:70:12
System.err:     Frame: function:'PageBase.eachChildView', file:'file: node_modules\@nativescript\core\ui\page\page-common.js:126:39
System.err:     Frame: function:'ViewCommon.eachChild', file:'file: node_modules\@nativescript\core\ui\core\view\view-common.js:915:13
System.err:     Frame: function:'ViewBase._setupUI', file:'file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:552:13
System.err:     Frame: function:'ViewBase._addViewCore', file:'file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:448:17
System.err:     Frame: function:'ViewBase._addView', file:'file: node_modules\@nativescript\core\ui\core\view-base\view-base.js:437:13
System.err:     Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file: node_modules\@nativescript\core\ui\frame\frame.android.js:700:18
System.err:     Frame: function:'FragmentClass.onCreateView', file:'file: node_modules\@nativescript\core\ui\frame\fragment.android.js:29:37
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)        
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
System.err:     at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)     
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: android.view.InflateException: Binary XML file line #18: Binary XML file line 
#18: Error inflating class com.google.android.material.textfield.TextInputLayout
System.err: Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class com.google.android.material.textfield.TextInputLayout
System.err: Caused by: java.lang.reflect.InvocationTargetException
System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:647)
System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
System.err:     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)        
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
System.err:     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
System.err:     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
System.err:     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
System.err:     at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: java.lang.IllegalArgumentException: The style on this component requires your 
app theme to be Theme.MaterialComponents (or a descendant).
System.err:     at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:248)
System.err:     at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:222)
System.err:     at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:150)
System.err:     at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:120)
System.err:     at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:424)
System.err:     at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:396)
System.err:     ... 31 more
```

**Comment by farfromrefug** [comment]
If you look closely at your log you will see the real error:
The style on this component requires your 
app theme to be Theme.MaterialComponents

**Comment by pazfelipe** [comment]
And how can I do that? I'm newbie with nativescript.

**Comment by farfromrefug** [comment]
@pazfelipe google is your friend. Simply searching the error:
https://stackoverflow.com/questions/53476115/error-illegalargumentexception-the-style-on-this-component-requires-your-app
