### ISSUE TITLE
Usage of org.nativescript.widgets.TextInputEditText

### ISSUE THREAD

**Issue by danielgek** [Akylas/nativescript-material-components#23]
On this [line](https://github.com/Akylas/nativescript-material-components/blob/master/src/textfield/textfield.android.ts#L33) you use `org.nativescript.widgets.TextInputEditText`, running for android sometimes shows error about that java class missing and i can't really find it anywhere xD Do you mind to explain why its there and why sometimes it just runs fine ?

Also, do you have any strategy to fix the typing errors on all packages  ?

**Comment by danielgek** [comment]
Humm that explains it all its was happening and a complication with errors and noemitter flag on disabled

What about the types ? Do you have a plan ?

**Comment by farfromrefug** [comment]
sorry but no.log no fix as I cant reproduce. also what about the typings? please try to be clearer

**Comment by danielgek** [comment]
@farfromrefug got it again, to reproduce it: rm -rf platform folder and have a typescript error on the app code, so it will throw an error when running `tns run`  for the first time, next compilations/hmr refreshes present the error below, to fix it needed to fix the error that has and also clean  platforms/android folder again

```
System.err: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err:
System.err: Error: java.lang.ClassNotFoundException: org.nativescript.widgets.TextInputEditText
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1123)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:679)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
System.err:     android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err:     android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err:     android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err:     android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err:     android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err:     android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err:     android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err:     android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err:     android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err:     android.os.Handler.handleCallback(Handler.java:873)
System.err:     android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.widgets.TextInputEditText" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.nativescript.Lands-FmJDrQrZPnX8XiO26rkrBA==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.Lands-FmJDrQrZPnX8XiO26rkrBA==/lib/x86, /data/app/org.nativescript.Lands-FmJDrQrZPnX8XiO26rkrBA==/base.apk!/lib/x86, /system/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1123)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:679)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err:     android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
System.err:     android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err:     android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err:     android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err:     android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err:     android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err:     android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err:     android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err:     android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err:     android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err:     android.os.Handler.handleCallback(Handler.java:873)
System.err:     android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     android.os.Looper.loop(Looper.java:193)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: File: "/data/data/org.nativescript.Lands/files/internal/ts_helpers.js, line: 154, column: 25
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'', file:'/data/data/org.nativescript.Lands/files/internal/ts_helpers.js', line: 154, column: 26
System.err: 	Frame: function:'DecorateConstructor', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 152099, column: 33
System.err: 	Frame: function:'decorate', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 151688, column: 24
System.err: 	Frame: function:'__decorate', file:'/data/data/org.nativescript.Lands/files/internal/ts_helpers.js', line: 8, column: 23
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 140416, column: 33
System.err: 	Frame: function:'initTextInputEditText', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 140421, column: 6
System.err: 	Frame: function:'push.../node_modules/nativescript-material-textfield/textfield.js.TextField.createNativeView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 140461, column: 9
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179877, column: 31
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179919, column: 19
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 188559, column: 26
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 181153, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179918, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179919, column: 19
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 188559, column: 26
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 181153, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179918, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179919, column: 19
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/content-view/content-view.js.ContentView.eachChildView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 177713, column: 13
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 181153, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179918, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179919, column: 19
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 188559, column: 26
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 181153, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179918, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179919, column: 19
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 188559, column: 26
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 181153, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179918, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179919, column: 19
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/content-view/content-view.js.ContentView.eachChildView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 177713, column: 13
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/page/page-common.js.PageBase.eachChildView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 189652, column: 40
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.eachChild', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 181153, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._setupUI', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179918, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addViewCore', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179817, column: 18
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 179806, column: 14
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 185697, column: 19
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/fragment.js.FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.Lands/files/app/vendor.js', line: 183702, column: 38
System.err:
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err: 	at com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
System.err: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
System.err: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
System.err: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
System.err: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
System.err: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: java.lang.ClassNotFoundException: org.nativescript.widgets.TextInputEditText
System.err: 	at java.lang.Class.classForName(Native Method)
System.err: 	at java.lang.Class.forName(Class.java:453)
System.err: 	at java.lang.Class.forName(Class.java:378)
System.err: 	at com.tns.Runtime.getClassForName(Runtime.java:1123)
System.err: 	at com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err: 	at com.tns.Runtime.resolveClass(Runtime.java:679)
System.err: 	... 24 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.nativescript.widgets.TextInputEditText" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.nativescript.Lands-FmJDrQrZPnX8XiO26rkrBA==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.Lands-FmJDrQrZPnX8XiO26rkrBA==/lib/x86, /data/app/org.nativescript.Lands-FmJDrQrZPnX8XiO26rkrBA==/base.apk!/lib/x86, /system/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err: 	... 30 more
```

**Comment by farfromrefug** [comment]
it s  an issue with the build not the module. the java classis not generated I guess. what some you tns  cli  versions?

**Comment by danielgek** [comment]
Yep that was my guess too, i'm on latest stable with the new workflow(webpack)
Getting NativeScript components versions information...
✔ Component nativescript has 5.4.0 version and is up to date.
✔ Component tns-core-modules has 5.4.2 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.

**Comment by farfromrefug** [comment]
ok seems fine. Now there are a lot of things which could make it not generate Java files. And it's tough because there is no error report during build :s 
You can look at your platform folder. If it works it should look like that
<img width="420" alt="Screen Shot 2019-06-16 at 18 40 00" src="https://user-images.githubusercontent.com/655344/59566881-38789000-9066-11e9-82f8-121c013bcc30.png">
