### ISSUE TITLE
Bottom sheets doesn't load the xml file

### ISSUE THREAD

**Issue by shiv19** [Akylas/nativescript-material-components#5]
I've created a nativescript modal page in the path, modal/modal-page

when I do
```
viewModel.buttonTap = function(args) {
        const mainView = args.object;
        const context = { username: "test_username", password: "test" };
        const fullscreen = true;
        mainView.showBottomSheet("modal/modal-page", context, (username, password) => {
            // Receive data from the bottomsheet view. e.g. username & password
            alert(`Username: ${username} : Password: ${password}`);
        }, fullscreen);
    }
```

I get the following error

```
System.err: com.tns.NativeScriptException:
System.err: Calling js method onClick failed
System.err:
System.err: Error: Failed to load page XML file for module: undefined
System.err: File: "file:///data/data/org.nativescript.materialtest/files/app/vendor.js, line: 13616, column: 4
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.materialtest/files/app/vendor.js', line: 13616, column: 11
System.err:     Frame: function:'push.../node_modules/nativescript-material-bottomsheet/bottomsheet-common.js.ViewWithBottomSheetBase.showBottomSheet', file:'file:///data/data/org.nativescript.materialtest/files/app/vendor.js', line: 387, column: 99
System.err:     Frame: function:'viewModel.buttonTap', file:'file:///data/data/org.nativescript.materialtest/files/app/bundle.js', line: 1087, column: 18
System.err:     Frame: function:'push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify', file:'file:///data/data/org.nativescript.materialtest/files/app/vendor.js', line: 4670, column: 32
System.err:     Frame: function:'push.../node_modules/tns-core-modules/data/observable/observable.js.Observable._emit', file:'file:///data/data/org.nativescript.materialtest/files/app/vendor.js', line: 4690, column: 18
System.err:     Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/org.nativescript.materialtest/files/app/vendor.js', line: 14408, column: 23
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     at java.lang.Object_vendor_14401_32_ClickListenerImpl.onClick(Unknown Source:10)
System.err:     at android.view.View.performClick(View.java:6669)
System.err:     at android.view.View.performClickInternal(View.java:6638)
System.err:     at android.view.View.access$3100(View.java:789)
System.err:     at android.view.View$PerformClick.run(View.java:26145)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6863)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

I have initialized it in app.js, the overriding part is working fine
```JS: about to override bottom sheet
JS: overrinding constructor
JS: overrinding _raiseShownBottomSheetEvent
JS: overrinding _bottomSheetClosed
JS: overrinding _showNativeBottomSheet
JS: overrinding _raiseShowingBottomSheetEvent
JS: overrinding closeBottomSheet
JS: overrinding showBottomSheet
JS: overrinding constructor
JS: overrinding _hideNativeBottomSheet
JS: overrinding _showNativeBottomSheet```

**Comment by farfromrefug** [comment]
@shiv19 sorry there is an error in the doc.
You have to do something like [this](https://github.com/Akylas/nativescript-material-components/blob/9546fc60b6052a3b46c74ac89ff81dcefbb3567f/demo/app/examples/example-page.ts#L90).
Will fix the doc as soon as possible!

**Comment by shiv19** [comment]
```mainView.showBottomSheet({view: "modal-page/modal-page", context, closeCallback: (username, password) => {
            // Receive data from the bottomsheet view. e.g. username & password
            alert(`Username: ${username} : Password: ${password}`);
        }, fullscreen: true});```

yes just realised, it is working now

**Comment by shiv19** [comment]
Sure :)

**Comment by farfromrefug** [comment]
@shiv19 The demo should work. But it needs the packages to be built first with lerna.
One alternative is to add the ```--bundle --env.development```.
this should build modules on the fly

**Comment by shiv19** [comment]
I did install lerna and run `npm run tsc` which built all the packages.
With the exception of bottomsheets package, which complained that it couldn't find nativescript-vue,
I deleted the vue folder from src/n-m-bottomsheet and then did a `npm run tsc` for that.

But when I built the demo, it couldn't find the packages for some reason.

**Comment by farfromrefug** [comment]
oh you are running the vue wip branch? which os are you on?

**Comment by shiv19** [comment]
I'm running master branch.
You can see that on master src/bottomsheet there is a vue folder.

I'm on Mac OS Mojave
Node: v10.12.0
Npm: v6.7.0

**Comment by farfromrefug** [comment]
@shiv19 ok must be outdated then. @msaelices is working on Vue integration right now https://github.com/Akylas/nativescript-material-components/pull/2
