### ISSUE TITLE
Crash BottomSheet in IOS 10

### ISSUE THREAD

**Issue by fvdung** [Akylas/nativescript-material-components#70]
### Which platform(s) does your issue occur on?
- iOS
- iOS 10
- emulator and device (Iphone 6, ios 10.x)

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) latest version

### Please, tell us how to recreate the issue in as much detail as possible. 
- Demo with Nativescript-Vue

### Is there any code involved? 
 I catch  log error 
```
JavaScript error:
file:///node_modules/nativescript-material-bottomsheet/bottomsheet.js:76:0: JS ERROR TypeError: undefined is not an object (evaluating 'layoutGuide.layoutFrame')
NativeScript caught signal 11.
Native Stack:
1   0x10e707cb1 sig_handler(int)
2   0x11716db1d _sigtramp
3   0x10e6290e0
4   0x1170bbcb6 libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step()
5   0x1170bfe68 _Unwind_RaiseException
6   0x116cc29a2 __cxa_throw
7   0x115caa268 _objc_exception_destructor(void*)
8   0x10e6bdbbf NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
9   0x10e6f9b28 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
10  0x10f0a5756 ffi_closure_unix64_inner
11  0x10f0a617a ffi_closure_unix64
12  0x114e90904 -[CALayer layoutSublayers]
13  0x114e84526 CA::Layer::layout_if_needed(CA::Transaction*)
14  0x10fe03334 -[UIView(Hierarchy) layoutBelowIfNeeded]
15  0x114830fbc -[MDCBottomSheetController viewWillAppear:]
16  0x10fefabad -[UIViewController _setViewAppearState:isAnimating:]
17  0x10fefb3c3 -[UIViewController __viewWillAppear:]
18  0x10fed0f87 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke
19  0x10fd5e853 _runAfterCACommitDeferredBlocks
20  0x10fd4b81c _cleanUpAfterCAFlushAndRunDeferredBlocks
21  0x10fd7d560 _afterCACommitHandler
22  0x1161e4717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
23  0x1161e4687 __CFRunLoopDoObservers
24  0x1161c9720 __CFRunLoopRun
25  0x1161c9016 CFRunLoopRunSpecific
26  0x117846a24 GSEventRunModal
27  0x10fd52134 UIApplicationMain
28  0x10f0a5fbd ffi_call_unix64
29  0x12d15ce90
JS Stack:
UIApplicationMain([native code])
at _start(file:///node_modules/tns-core-modules/application/application.js:295:0)
at run(file:///node_modules/tns-core-modules/application/application.js:323:0)
at $start(file:///node_modules/nativescript-vue/dist/index.js:14050:0)
at file:///app/bundle.js:21915:10
at ./app.js(file:///app/bundle.js:21919:34)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at checkDeferredModules(file:///app/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///app/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at promiseReactionJob
```

### Relation
Perhaps this exception relate to this merge request
[https://github.com/NativeScript/NativeScript/pull/5960/files](https://github.com/NativeScript/NativeScript/pull/5960/files)

**Comment by farfromrefug** [comment]
@fvdung i ll close this for now. If you still ssee this please post a sample project
