### ISSUE TITLE
[Android] Crash when supplying options to snackbar

### ISSUE THREAD

**Issue by izub** [Akylas/nativescript-material-components#73]
### Which platform(s) does your issue occur on?
- Android 8.0.0
- Samsung Galaxy S7

### Please, provide the following version numbers that your issue occurs with:
CLI: 6.1.2
Cross-platform modules: 6.1.1
Runtime(s): tns-android: 6.1.2
Plugin(s): nativescript-material-snackbar: 2.5.2, nativescript-angular: 8.2.1

### Please, tell us how to recreate the issue in as much detail as possible. 
Calling the method of the code in the section below will result in a crash with the following exception:
```
System.err: Error: Uncaught (in promise): TypeError: Cannot read property 'setTextColor' of null
System.err: TypeError: Cannot read property 'setTextColor' of null
System.err:     at SnackBar.push.../node_modules/nativescript-material-snackbar/snackbar.js.SnackBar.initSnack (file:///node_modules/nativescript-material-snackbar/snackbar.js:62:0)
System.err:     at file:///node_modules/nativescript-material-snackbar/snackbar.js:116:0
System.err:     at new ZoneAwarePromise (file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)
System.err:     at SnackBar.push.../node_modules/nativescript-material-snackbar/snackbar.js.SnackBar.show (file:///node_modules/nativescript-material-snackbar/snackbar.js:113:0)
System.err:     at SnackBar.push.../node_modules/nativescript-material-snackbar/snackbar-common.js.SnackBarBase.showSnack (file:///node_modules/nativescript-material-snackbar/snackbar-common.js:42:0)
System.err:     at SnackBar.push.../node_modules/nativescript-material-snackbar/snackbar-common.js.SnackBarBase.simple (file:///node_modules/nativescript-material-snackbar/snackbar-common.js:22:0)
System.err:     at SecureComponent.showSnackbar (file:///src/app/secure/secure.component.ts:60:17)
```

Simply calling `snackbar.simple(message)` without options displays the snackbar without any issues.

### Is there any code involved? 
```
showSnackbar(message: string) {
        const snackbar = new SnackBar();
        snackbar.simple(message, '#ffffff', '#4f5154');
}
```

**Comment by farfromrefug** [comment]
@izub i see the issue. It s related to the version of the android material lib. 
Should be fixed in 2.5.3
