### ISSUE TITLE
[BottomSheet] Crash when dismissing

### ISSUE THREAD

**Issue by kryoware** [Akylas/nativescript-material-components#98]
### Which platform(s) does your issue occur on?
- Android
- Android versions: 9.x
- emulator or device. What type of device? Nokia 8 / Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.2.2
- Cross-platform modules: 6.2.1
- Runtime(s): 6.2.0
- Plugin(s):
```
  "dependencies": {
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "@vue/devtools": "^5.3.2",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0.19",
    "apollo-link-http": "^1.5.16",
    "graphql": "^14.5.4",
    "graphql-tag": "^2.10.1",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "nativescript-background-http": "^4.2.1",
    "nativescript-camera": "^4.5.0",
    "nativescript-carousel": "^6.1.0",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-image-swipe": "^5.0.1",
    "nativescript-imagepicker": "^6.3.0",
    "nativescript-local-notifications": "^4.1.4",
    "nativescript-lottie": "^4.0.0",
    "nativescript-material-bottomsheet": "^3.0.6",
    "nativescript-permissions": "^1.3.7",
    "nativescript-phone": "^1.4.1",
    "nativescript-plugin-firebase": "^10.1.1",
    "nativescript-ripple": "^2.2.1",
    "nativescript-sentry": "^1.9.1",
    "nativescript-socketio": "^3.3.1",
    "nativescript-ui-autocomplete": "^5.1.1",
    "nativescript-ui-listview": "^8.0.1",
    "nativescript-unit-test-runner": "^0.7.0",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.2.0",
    "nativescript-vue-shadow": "^0.1.0",
    "nativescript-web-image-cache": "^5.0.0",
    "tns-core-modules": "^6.2.1",
    "vue-apollo": "^3.0.0",
    "vue-moment": "^4.0.0",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.7.2",
    "@babel/preset-env": "^7.7.1",
    "@fortawesome/fontawesome-free": "^5.10.2",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "chai": "4.2.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "karma": "4.2.0",
    "karma-chai": "0.1.0",
    "karma-mocha": "1.3.0",
    "karma-nativescript-launcher": "0.4.0",
    "karma-webpack": "4.0.2",
    "lazy": "1.0.11",
    "mocha": "6.2.0",
    "nativescript-dev-webpack": "~1.3.0",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.13.0",
    "sass-loader": "^7.3.1",
    "terser-webpack-plugin": "^1.4.1",
    "tns-platform-declarations": "^6.2.1",
    "vue-loader": "^15.7.2",
    "webpack": "^4.41.2",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.3.10"
  }
```
### Is there any code involved? 
OrderPage.vue Component - Just a basic button with `@tap="showBottomSheet"` code below for how I set it up
```
    showBottomSheet() {
      const { closeCallback } = this

      this.$showBottomSheet(RateBuyer, {
        props: {
          closeCallback
        }
      })
    },
    closeCallback(result) {
      console.warn({ result })
    },
```

RateBuyer.vue Component
```
<template>
  <StackLayout height="164" ref="bottomSheet">
    <FlexboxLayout justifyContent="space-between" marginTop="22" marginRight="72" marginLeft="72">
      <Image src="res://ic_star_empty" width="32" height="32" stretch="aspectFit" @tap="onTap" />
      <Image src="res://ic_star_empty" width="32" height="32" stretch="aspectFit" />
      <Image src="res://ic_star_empty" width="32" height="32" stretch="aspectFit" />
      <Image src="res://ic_star_empty" width="32" height="32" stretch="aspectFit" />
      <Image src="res://ic_star_empty" width="32" height="32" stretch="aspectFit" />
    </FlexboxLayout>

    <Button
      text="Submit"
      classes="__btn-primary __fs-14"
      @tap.native="onTap"
      marginTop="24"
      marginBottom="24"
      marginRight="72"
      marginLeft="72"
    />

    <FlexboxLayout justifyContent="center" ref="contact" opacity="0">
      <Label
        text="Contact Support"
        class="__text-norm __text-primary __fs-14"
      />
    </FlexboxLayout>
  </StackLayout>
</template>

<script>
export default {
  methods: {
    onTap(args) {
      console.warn('Tapped!')
    }
  }
}
</script>
```

Everything works perfectly fine until I try to close the bottom sheet. The app crashes and shows this error:
```2020-01-09 10:19:01.895 1763-1763/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 1763
    com.tns.NativeScriptException: Calling js method onDismiss failed
    TypeError: Cannot read property 'setOnTouchListener' of null
        at com.tns.Runtime.callJSMethodNative(Native Method)
        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
        at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
        at com.tns.Runtime.callJSMethod(Runtime.java:1160)
        at com.tns.Runtime.callJSMethod(Runtime.java:1138)
        at com.tns.Runtime.callJSMethod(Runtime.java:1134)
        at com.tns.gen.com.google.android.material.bottomsheet.BottomSheetDialogFragment_vendor_91502_26_BottomSheetDialogFragmentImpl.onDismiss(BottomSheetDialogFragment_vendor_91502_26_BottomSheetDialogFragmentImpl.java:26)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1393)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err: Calling js method onDismiss failed
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err: View.onUnloaded(file:///data/data/com.example.app/files/app/vendor.js:22790:32)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at (file:///data/data/com.example.app/files/app/vendor.js:20471:20)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.callFunctionWithSuper(file:///data/data/com.example.app/files/app/vendor.js:20452:5)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.callUnloaded(file:///data/data/com.example.app/files/app/vendor.js:20470:10)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.unloadView(file:///data/data/com.example.app/files/app/vendor.js:20645:12)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at (file:///data/data/com.example.app/files/app/vendor.js:20383:13)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at LayoutBaseCommon.eachChildView(file:///data/data/com.example.app/files/app/vendor.js:32262:20)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewCommon.eachChild(file:///data/data/com.example.app/files/app/vendor.js:22243:10)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.onUnloaded(file:///data/data/com.example.app/files/app/vendor.js:20382:10)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at View.onUnloaded(file:///data/data/com.example.app/files/app/vendor.js:22798:33)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at (file:///data/data/com.example.app/files/app/vendor.js:20471:20)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.callFunctionWithSuper(file:///data/data/com.example.app/files/app/vendor.js:20452:5)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.callUnloaded(file:///data/data/com.example.app/files/app/vendor.js:20470:10)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.unloadView(file:///data/data/com.example.app/files/app/vendor.js:20645:12)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at (file:///data/data/com.example.app/files/app/vendor.js:20383:13)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at LayoutBaseCommon.eachChildView(file:///data/data/com.example.app/files/app/vendor.js:32262:20)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewCommon.eachChild(file:///data/data/com.example.app/files/app/vendor.js:22243:10)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.onUnloaded(file:///data/data/com.example.app/files/app/vendor.js:20382:10)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at View.onUnloaded(file:///data/data/com.example.app/files/app/vendor.js:22798:33)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at (file:///data/data/com.example.app/files/app/vendor.js:20471:20)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.callFunctionWithSuper(file:///data/data/com.example.app/files/app/vendor.js:20452:5)
2020-01-09 10:19:01.966 1763-1763/com.example.app W/System.err:     at ViewBase.callUnloaded(file:///data/data/com.example.app/files/app/vendor.js:20470:10)
2020-01-09 10:19:01.967 1763-1763/com.example.app W/System.err:     at BottomSheetDialogFragmentImpl.onDismiss(file:///data/data/com.example.app/files/app/vendor.js:91590:15)
2020-01-09 10:19:01.967 1763-1763/com.example.app W/System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
2020-01-09 10:19:01.967 1763-1763/com.example.app W/System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
2020-01-09 10:19:01.967 1763-1763/com.example.app W/System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
2020-01-09 10:19:01.967 1763-1763/com.example.app W/System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
2020-01-09 10:19:01.967 1763-1763/com.example.app W/System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
2020-01-09 10:19:01.967 1763-1763/com.example.app W/System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
```

**Comment by farfromrefug** [comment]
duplicate https://github.com/Akylas/nativescript-material-components/issues/71
